const employees = [
  {"name":"Alice","department":"HR","age":29,"email":"alice.hr@example.com","city":"New York"},
  {"name":"Bob","department":"IT","age":35,"email":"bob.it@example.com","city":"San Francisco"},
  {"name":"Charlie","department":"Finance","age":40,"email":"charlie.finance@example.com","city":"Chicago"},
  {"name":"David","department":"Marketing","age":25,"email":"david.marketing@example.com","city":"Los Angeles"},
  {"name":"Eva","department":"Sales","age":32,"email":"eva.sales@example.com","city":"Miami"},
  {"name":"Frank","department":"Operations","age":28,"email":"frank.operations@example.com","city":"Austin"},
  {"name":"Grace","department":"IT","age":30,"email":"grace.it@example.com","city":"San Francisco"},
  {"name":"Hannah","department":"Finance","age":38,"email":"hannah.finance@example.com","city":"Chicago"},
  {"name":"Ivy","department":"HR","age":27,"email":"ivy.hr@example.com","city":"New York"},
  {"name":"James","department":"Marketing","age":33,"email":"james.marketing@example.com","city":"Los Angeles"},
  {"name":"Kelly","department":"Sales","age":36,"email":"kelly.sales@example.com","city":"Miami"},
  {"name":"Liam","department":"Operations","age":31,"email":"liam.operations@example.com","city":"Austin"},
  {"name":"Megan","department":"IT","age":26,"email":"megan.it@example.com","city":"San Francisco"},
  {"name":"Nina","department":"HR","age":41,"email":"nina.hr@example.com","city":"New York"},
  {"name":"Oscar","department":"Finance","age":34,"email":"oscar.finance@example.com","city":"Chicago"},
  {"name":"Paul","department":"Marketing","age":29,"email":"paul.marketing@example.com","city":"Los Angeles"},
  {"name":"Quincy","department":"Sales","age":37,"email":"quincy.sales@example.com","city":"Miami"},
  {"name":"Rachel","department":"Operations","age":39,"email":"rachel.operations@example.com","city":"Austin"},
  {"name":"Sam","department":"IT","age":27,"email":"sam.it@example.com","city":"San Francisco"},
  {"name":"Tina","department":"HR","age":31,"email":"tina.hr@example.com","city":"New York"}
];
